## copiar este archivo a ../../settings/
routes:
  /request-quote/: cotizar
  /cotizar/: cotizar
  /en/: home
collections:
  /:
    permalink: /{slug}/
    template: home
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
