## copiar este archivo a ../../settings/
routes:
  /request-quote/: cotizar
  /cotizar/: cotizar
  /en/:
    data: page.agencia-en
    template: index
  /:
    data: page.agencia
    template: index
collections:
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
