## copiar este archivo a ../../settings/
routes:
  /request-quote/: cotizar
  /cotizar/: cotizar
  /en/: index
collections:
  /:
    permalink: /{slug}/
    template: index
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
