## copiar este archivo a ../../settings/
routes:
  /en/: home
collections:
  /:
    permalink: /{slug}/
    template: index
  /request-quote/:
    permalink: /request-quote/
    template: cotizar
  /cotizar/:
    permalink: /cotizar/
    template: cotizar


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
